databaseChangeLog:
  - changeSet:
      id: tag
      author: snikitin
      changes:
        - tagDatabase:
            tag: 027-add-ha-flow-feature-toggle
  - changeSet:
      id: add_ha_flow_affinity_and_diverse_groups
      author: snikitin
      changes:
        - sql: "CREATE PROPERTY ha_flow.diverse_group_id IF NOT EXISTS STRING"
        - sql: "CREATE PROPERTY ha_flow.affinity_group_id IF NOT EXISTS STRING"
        - sql: "CREATE INDEX ha_flow.diverse_group_id NOTUNIQUE_HASH_INDEX"
        - sql: "CREATE INDEX ha_flow.affinity_group_id NOTUNIQUE_HASH_INDEX"
      rollback:
        - sql: "DROP INDEX ha_flow.diverse_group_id"
        - sql: "DROP INDEX ha_flow.affinity_group_id"
        - sql: "UPDATE ha_flow REMOVE diverse_group_id"
        - sql: "UPDATE ha_flow REMOVE affinity_group_id"
        - sql: "DROP PROPERTY ha_flow.diverse_group_id"
        - sql: "DROP PROPERTY ha_flow.affinity_group_id"
